theme: jekyll-theme-minimal
title: Shadoral's homepage
description: o w o)v caffeine vow….coffee grant me strength…cookie blade… <p><blockquote> I left the woods for as good a reason as I went there.  Perhaps it seemed to me that I had several more lives to live, and could not spare more time for that one. </blockquote></p>
